---
title: "Case Study 01"
author: "Hudson"
date: "2/17/2022"
output: html_document
---

```{r}
#read in the datasets
library(readr)
beer = read_csv("C:\\Users\\Hudson\\OneDrive\\Documents\\Josh - Masters\\Doing Data Science - MSDS_6306\\Case Study 1\\Beers.csv")
brew = read_csv("C:\\Users\\Hudson\\OneDrive\\Documents\\Josh - Masters\\Doing Data Science - MSDS_6306\\Case Study 1\\Breweries.csv")

```

```{r}
#load the needed libraries
library(ggplot2)
library(GGally)
library(magrittr)
library(dplyr)
library(tidyverse)
library(usmap)
library(maps)
library(mapproj)
library(fiftystater)
```

Analysis Questions:
1.How many breweries are present in each state?
```{r}
#1.How many breweries are present in each state?
st_count = brew %>% group_by(State) %>% summarize(Count =n_distinct(Brew_ID))  

colnames(st_count)[1] = "abb" #rename state to abb for future merge
lookup = data.frame(abb = state.abb, State = state.name) #load in state names and state abbreviations to a dataframe for future merge
st_count = merge(st_count,lookup,"abb") #make a single data set with state names and abbreviations
st_count$region <- tolower(st_count$State) #make all state names lowercase for future merge
st_count = st_count[-1]
#states = map_data("state")
colnames(fifty_states)[6] = "region"
st_count = merge(fifty_states, st_count, by = "region", all.x = T) #merge the dateframes to include regions
st_count = st_count[order(st_count$order),] #order the dataframe to paint a proper map

st_count %>% ggplot(aes(x = fifty_states$long, y = fifty_states$lat, group = group)) + geom_polygon(aes(fill = Count)) + geom_path() + scale_fill_gradientn(colors = hcl.colors(10, "RdYlGn", rev = TRUE), na.value = "grey90")+ggtitle("Number of Breweries in Each State") + coord_quickmap()#plot the heatmap

```
2.   Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file.  (RMD only, this does not need to be included in the presentation or the deck.)
```{r}
colnames(beer)[5] = "Brew_ID"  #rename brewery ID in Beers data to match Breweries data's brewery ID for future merge
colnames(beer)[1] = "Beer Name" #delineates between beer name and brewery names
colnames(brew)[2] = "Brewery Name"

bb = merge(beer, brew, by = "Brew_ID", all.x = T) #make the merge
head(bb) #1st six observations
tail(bb) #last six observations
```

3.   Address the missing values in each column.
```{r}

```